from tkinter import *
main=Tk()
def l_button_click():
    print('login button clicked')
def c_button_click():
    print('clear button clicked')
main.title("window1")
tframe=Frame(main)
bframe=Frame(main)
tframe.pack()
bframe.pack(side=BOTTOM)
label1=Label(main,text='username')
label2=Label(main,text='password')
entry1=Entry(main)
entry2=Entry(main)
label1.pack()
entry1.pack()
label2.pack()
entry2.pack()
btn1=Button(bframe,text='LOGIN',fg='blue',bg='yellow',command=l_button_click)
btn2=Button(bframe,text='Clear',fg='blue',bg='yellow',command=c_button_click)
btn1.pack(side=LEFT)
btn2.pack(side=RIGHT)
main.mainloop()